graph LR
    DP_STG.NRT_OneLineTXNLogC2S_LIST[("DP_STG.NRT_OneLineTXNLogC2S_LIST")] -->|recharge_oneline_txn_log_c2s| DP_STG.NRT_OneLineTXNLogC2S_PROCESS_LIST[("DP_STG.NRT_OneLineTXNLogC2S_PROCESS_LIST")]
    DP_STG.NRT_OneLineTXNLogC2S_PROCESS_LIST[("DP_STG.NRT_OneLineTXNLogC2S_PROCESS_LIST")]
    dp_stg.NRT_EV_TRANSACTION_FROM_LOG[("dp_stg.NRT_EV_TRANSACTION_FROM_LOG")]
    dp_stg.NRT_EV_TRANSACTION_FROM_LOG[("dp_stg.NRT_EV_TRANSACTION_FROM_LOG")]
    DP_STG.ALL_FILE_LIST_IN_DIR_FOR_TXT_LOG_C2C[("DP_STG.ALL_FILE_LIST_IN_DIR_FOR_TXT_LOG_C2C")] -->|recharge_oneline_txn_log_c2c| DP_STG.PROCESSABLE_FILE_LIST_FOR_TXT_LOG_C2C[("DP_STG.PROCESSABLE_FILE_LIST_FOR_TXT_LOG_C2C")]
    DP_STG.PROCESSABLE_FILE_LIST_FOR_TXT_LOG_C2C[("DP_STG.PROCESSABLE_FILE_LIST_FOR_TXT_LOG_C2C")]
    DP_STG.TXT_LOG_C2C_EXTRACTION[("DP_STG.TXT_LOG_C2C_EXTRACTION")]
    DP_STG.TXT_LOG_C2C_EXTRACTION[("DP_STG.TXT_LOG_C2C_EXTRACTION")] -->|recharge_oneline_txn_log_c2c| DP_STG.TXT_LOG_C2C_LD[("DP_STG.TXT_LOG_C2C_LD")]
    DP_STG.TXT_LOG_C2C_LD[("DP_STG.TXT_LOG_C2C_LD")] -->|recharge_oneline_txn_log_c2c| DP_STG.NRT_EV_TRANSACTION_FROM_LOG[("DP_STG.NRT_EV_TRANSACTION_FROM_LOG")]
    DP_STG.PROCESSABLE_FILE_LIST_FOR_TXT_LOG_C2C[("DP_STG.PROCESSABLE_FILE_LIST_FOR_TXT_LOG_C2C")] -->|recharge_oneline_txn_log_c2c| DP_STG.ALREADY_PROCESSED_FILE_LIST_FOR_TXT_LOG_C2C[("DP_STG.ALREADY_PROCESSED_FILE_LIST_FOR_TXT_LOG_C2C")]
    DP_STG.NRT_CDR_LIST[("DP_STG.NRT_CDR_LIST")] -->|recharge_nrt_cdr| DP_STG.NRT_CDR_PROCESS_LIST[("DP_STG.NRT_CDR_PROCESS_LIST")]
    DP_STG.NRT_CDR_PROCESS_LIST[("DP_STG.NRT_CDR_PROCESS_LIST")]
    DP_STG.NRT_X_AIR_REFILL_TMP[("DP_STG.NRT_X_AIR_REFILL_TMP")]
    DP_STG.NRT_X_AIR_REFILL_TMP[("DP_STG.NRT_X_AIR_REFILL_TMP")] -->|recharge_nrt_cdr| DP_STG.NRT_X_AIR_REFILL[("DP_STG.NRT_X_AIR_REFILL")]
    dp_etl_vew.recharge_sdp_pam_ld[("dp_etl_vew.recharge_sdp_pam_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_fct[("dp_tab.recharge_fct")]
    dp_etl_vew.recharge_sdp_pam_da_ld[("dp_etl_vew.recharge_sdp_pam_da_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_da_fct[("dp_tab.recharge_da_fct")]
    dp_etl_vew.recharge_air_adjustment_ld[("dp_etl_vew.recharge_air_adjustment_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_fct[("dp_tab.recharge_fct")]
    dp_etl_vew.recharge_air_adjust_da_ld[("dp_etl_vew.recharge_air_adjust_da_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_da_fct[("dp_tab.recharge_da_fct")]
    dp_etl_vew.recharge_air_refill_ld[("dp_etl_vew.recharge_air_refill_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_fct[("dp_tab.recharge_fct")]
    dp_STG.RECHARGE_AIR_REFILL_DA_LD[("dp_STG.RECHARGE_AIR_REFILL_DA_LD")] -->|recharge_eric_recharge_loading| dp_STG.RECHARGE_AIR_REFILL_DA_LD_DEL[("dp_STG.RECHARGE_AIR_REFILL_DA_LD_DEL")]
    dp_etl_vew.recharge_air_refill_da_ld[("dp_etl_vew.recharge_air_refill_da_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_da_fct[("dp_tab.recharge_da_fct")]
    dp_etl_vew.recharge_SDP_LIFE_CYCLE_ld[("dp_etl_vew.recharge_SDP_LIFE_CYCLE_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_fct[("dp_tab.recharge_fct")]
    dp_etl_vew.recharge_ccn_bonus_ld[("dp_etl_vew.recharge_ccn_bonus_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_fct[("dp_tab.recharge_fct")]
    dp_etl_vew.recharge_ccn_bonus_da_ld[("dp_etl_vew.recharge_ccn_bonus_da_ld")] -->|recharge_eric_recharge_loading| dp_tab.recharge_da_fct[("dp_tab.recharge_da_fct")]
    dp_stg.ETL_SDP_PURPOSE[("dp_stg.ETL_SDP_PURPOSE")] -->|recharge_eric_recharge_loading| RPD[("RPD")]
    dp_stg.X_AIR_REFILL_FILENAME[("dp_stg.X_AIR_REFILL_FILENAME")]
    dp_stg.X_AIR_REFILL_FILENAME[("dp_stg.X_AIR_REFILL_FILENAME")]
    dp_etl_vew.ETL_RECHARGE_CDR_INFO[("dp_etl_vew.ETL_RECHARGE_CDR_INFO")]
    dp_etl_vew.ETL_RECHARGE_CDR_INFO[("dp_etl_vew.ETL_RECHARGE_CDR_INFO")]
    dp_stg.etl_sd_ssf_lkp_db4y[("dp_stg.etl_sd_ssf_lkp_db4y")]
    dp_stg.etl_sd_ssf_lkp_y[("dp_stg.etl_sd_ssf_lkp_y")]
    dp_etl_vew.subscription_dim[("dp_etl_vew.subscription_dim")] -->|recharge_eric_recharge_initiator| dp_stg.etl_sd_ssf_lkp_db4y[("dp_stg.etl_sd_ssf_lkp_db4y")]
    dp_etl_vew.subscription_snapshot_fct[("dp_etl_vew.subscription_snapshot_fct")] -->|recharge_eric_recharge_initiator| dp_stg.etl_sd_ssf_lkp_db4y[("dp_stg.etl_sd_ssf_lkp_db4y")]
    dp_etl_vew.date_dim[("dp_etl_vew.date_dim")]
    dp_stg.etl_sd_ssf_lkp_y[("dp_stg.etl_sd_ssf_lkp_y")]
    dp_etl_vew.subscription_dim[("dp_etl_vew.subscription_dim")] -->|recharge_eric_recharge_initiator| dp_stg.etl_sd_ssf_lkp_y[("dp_stg.etl_sd_ssf_lkp_y")]
    DP_STG.ETL_SNPSHOT_FCT_NEW_PH01_KK[("DP_STG.ETL_SNPSHOT_FCT_NEW_PH01_KK")] -->|recharge_eric_recharge_initiator| dp_stg.etl_sd_ssf_lkp_y[("dp_stg.etl_sd_ssf_lkp_y")]
    DP_ETL_VEW.X_EV_TRANSACTION_STG[("DP_ETL_VEW.X_EV_TRANSACTION_STG")]
    DP_STG.X_EV_TRANSACTION_STG_BACKUP[("DP_STG.X_EV_TRANSACTION_STG_BACKUP")]
    DP_LOG.ETL_LOG_EV_TRANSACTION[("DP_LOG.ETL_LOG_EV_TRANSACTION")]
    DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1")] -->|recharge_sc_primary_lifting_transformation| DP_TAB.EV_TRANSACTION_TYPE_DIM[("DP_TAB.EV_TRANSACTION_TYPE_DIM")]
    DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1")] -->|recharge_sc_primary_lifting_transformation| DP_TAB.EV_CHANNEL_TYPE_DIM[("DP_TAB.EV_CHANNEL_TYPE_DIM")]
    DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1")] -->|recharge_sc_primary_lifting_transformation| DP_TAB.EV_CHANNEL_CATEGORY_DIM[("DP_TAB.EV_CHANNEL_CATEGORY_DIM")]
    DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1")] -->|recharge_sc_primary_lifting_transformation| DP_TAB.SC_PRODUCT_TYPE_DIM[("DP_TAB.SC_PRODUCT_TYPE_DIM")]
    DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1")] -->|recharge_sc_primary_lifting_transformation| DP_TAB.SALES_CHANNEL_DIM[("DP_TAB.SALES_CHANNEL_DIM")]
    DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_PRIMARY_LIFTING_STG1")]
    DP_ETL_VEW.SC_PRIMARY_LIFTING_LD[("DP_ETL_VEW.SC_PRIMARY_LIFTING_LD")]
    DP_ETL_VEW.SC_PRIMARY_LIFTING_ALL_LKP[("DP_ETL_VEW.SC_PRIMARY_LIFTING_ALL_LKP")]
    DP_LOG.ETL_LOG_EV_TRANSACTION[("DP_LOG.ETL_LOG_EV_TRANSACTION")]
    DP_ETL_VEW.S_SC_PRIMARY_LIFTING_LD[("DP_ETL_VEW.S_SC_PRIMARY_LIFTING_LD")] -->|recharge_sc_lifting_loading| DP_ETL_VEW.RECHARGE_CHANNEL_FCT[("DP_ETL_VEW.RECHARGE_CHANNEL_FCT")]
    DP_ETL_VEW.S_SC_SECONDARY_LIFTING_LD[("DP_ETL_VEW.S_SC_SECONDARY_LIFTING_LD")] -->|recharge_sc_lifting_loading| DP_ETL_VEW.RECHARGE_CHANNEL_FCT[("DP_ETL_VEW.RECHARGE_CHANNEL_FCT")]
    DMSPHASE4.SCTRANSACTION[("DMSPHASE4.SCTRANSACTION")] -->|recharge_SC_lifting_extraction| DP_STG.X_SC_SECONDARY_LIFTING[("DP_STG.X_SC_SECONDARY_LIFTING")]
    CFDB.TBLPRODUCT[("CFDB.TBLPRODUCT")] -->|recharge_SC_lifting_extraction| DP_STG.X_SC_SECONDARY_LIFTING[("DP_STG.X_SC_SECONDARY_LIFTING")]
    DMSPHASE4.DISTRIBUTOR[("DMSPHASE4.DISTRIBUTOR")] -->|recharge_SC_lifting_extraction| DP_STG.X_SC_SECONDARY_LIFTING[("DP_STG.X_SC_SECONDARY_LIFTING")]
    DMSPHASE4.RETAILER[("DMSPHASE4.RETAILER")] -->|recharge_SC_lifting_extraction| DP_STG.X_SC_SECONDARY_LIFTING[("DP_STG.X_SC_SECONDARY_LIFTING")]
    DMSPHASE4.RSO[("DMSPHASE4.RSO")] -->|recharge_SC_lifting_extraction| DP_STG.X_SC_SECONDARY_LIFTING[("DP_STG.X_SC_SECONDARY_LIFTING")]
    DMSPHASE4.RSO[("DMSPHASE4.RSO")] -->|recharge_SC_lifting_extraction| DP_STG.X_SC_SECONDARY_LIFTING[("DP_STG.X_SC_SECONDARY_LIFTING")]
    CFDB.TBLISSUEDETAULSWAREHOUSE[("CFDB.TBLISSUEDETAULSWAREHOUSE")] -->|recharge_SC_lifting_extraction| DP_STG_POS.X_SC_PRIMARY_LIFTING[("DP_STG_POS.X_SC_PRIMARY_LIFTING")]
    CFDB.TBLPRODUCT[("CFDB.TBLPRODUCT")] -->|recharge_SC_lifting_extraction| DP_STG_POS.X_SC_PRIMARY_LIFTING[("DP_STG_POS.X_SC_PRIMARY_LIFTING")]
    DP_ETL_VEW.X_SC_SECONDARY_LIFTING_STG1[("DP_ETL_VEW.X_SC_SECONDARY_LIFTING_STG1")] -->|recharge_sc_secondary_lifting_transformation| DP_ETL_VEW.X_SC_SECONDARY_LIFTING_STG2[("DP_ETL_VEW.X_SC_SECONDARY_LIFTING_STG2")]
    DP_ETL_VEW.X_SC_SECONDARY_LIFTING_STG2[("DP_ETL_VEW.X_SC_SECONDARY_LIFTING_STG2")] -->|recharge_sc_secondary_lifting_transformation| DP_TAB.EV_TRANSACTION_TYPE_DIM[("DP_TAB.EV_TRANSACTION_TYPE_DIM")]
    DP_ETL_VIEW.X_SC_SECONDARY_LIFTING_STG2[("DP_ETL_VIEW.X_SC_SECONDARY_LIFTING_STG2")] -->|recharge_sc_secondary_lifting_transformation| DP_TAB.EV_CHANNEL_TYPE_DIM[("DP_TAB.EV_CHANNEL_TYPE_DIM")]
    DP_ETL_VIEW.X_SC_SECONDARY_LIFTING_STG2[("DP_ETL_VIEW.X_SC_SECONDARY_LIFTING_STG2")] -->|recharge_sc_secondary_lifting_transformation| DP_TAB.EV_CHANNEL_CATEGORY_DIM[("DP_TAB.EV_CHANNEL_CATEGORY_DIM")]
    DP_ETL_VIEW.X_SC_SECONDARY_LIFTING_STG2[("DP_ETL_VIEW.X_SC_SECONDARY_LIFTING_STG2")] -->|recharge_sc_secondary_lifting_transformation| DP_TAB.SC_PRODUCT_TYPE_DIM[("DP_TAB.SC_PRODUCT_TYPE_DIM")]
    DP_ETL_VEW.SC_SECONDARY_LIFTING_LD[("DP_ETL_VEW.SC_SECONDARY_LIFTING_LD")]
    DP_LOG.ETL_LOG_EV_TRANSACTION[("DP_LOG.ETL_LOG_EV_TRANSACTION")]
    DP_ETL_VEW.S_EV_TRANSACTION_LD[("DP_ETL_VEW.S_EV_TRANSACTION_LD")] -->|recharge_ev_transaction_loading| DP_ETL_VEW.RECHARGE_CHANNEL_FCT[("DP_ETL_VEW.RECHARGE_CHANNEL_FCT")]
    DP_LOG.ETL_LOG_EV_TRANSACTION[("DP_LOG.ETL_LOG_EV_TRANSACTION")]
    DP_STG.EV_TRANS_COUNT_DTL[("DP_STG.EV_TRANS_COUNT_DTL")]
    DP_STG.X_EV_TRANSACTION_STG[("DP_STG.X_EV_TRANSACTION_STG")] -->|recharge_ev_transaction_transformation| X_EV_TRNS_VALID_RECORDS_N[("X_EV_TRNS_VALID_RECORDS_N")]
    X_EV_TRNS_VALID_RECORDS_N[("X_EV_TRNS_VALID_RECORDS_N")] -->|recharge_ev_transaction_transformation| X_EV_TRANSACTION_VALID_RECORDS[("X_EV_TRANSACTION_VALID_RECORDS")]
    DP_STG.X_EV_TRANSACTION_STG[("DP_STG.X_EV_TRANSACTION_STG")] -->|recharge_ev_transaction_transformation| DP_STG.BL_ETL_DAILY_SOURCE_QC[("DP_STG.BL_ETL_DAILY_SOURCE_QC")]
    DP_STG.BL_ETL_DAILY_SOURCE_QC[("DP_STG.BL_ETL_DAILY_SOURCE_QC")]
    DP_STG.X_EV_TRANSACTION_STG[("DP_STG.X_EV_TRANSACTION_STG")] -->|recharge_ev_transaction_transformation| DP_TAB.EV_TRANSACTION_TYPE_DIM[("DP_TAB.EV_TRANSACTION_TYPE_DIM")]
    DP_STG.X_EV_TRANSACTION_STG[("DP_STG.X_EV_TRANSACTION_STG")] -->|recharge_ev_transaction_transformation| DP_TAB.EV_CHANNEL_TYPE_DIM[("DP_TAB.EV_CHANNEL_TYPE_DIM")]
    DP_STG.X_EV_TRANSACTION_STG[("DP_STG.X_EV_TRANSACTION_STG")] -->|recharge_ev_transaction_transformation| DP_TAB.EV_CHANNEL_CATEGORY_DIM[("DP_TAB.EV_CHANNEL_CATEGORY_DIM")]
    DP_STG.X_EV_TRANSACTION_STG[("DP_STG.X_EV_TRANSACTION_STG")] -->|recharge_ev_transaction_transformation| DP_TAB.EV_COMMISSION_TYPE_DIM[("DP_TAB.EV_COMMISSION_TYPE_DIM")]
    DP_ETL_VEW.EV_TRANSACTION_ALL_LOOKUP[("DP_ETL_VEW.EV_TRANSACTION_ALL_LOOKUP")] -->|recharge_ev_transaction_transformation| DP_ETL_VEW.EV_TRANSACTION_LD[("DP_ETL_VEW.EV_TRANSACTION_LD")]
    DP_ETL_VEW.EV_TRANSACTION_ALL_LOOKUP[("DP_ETL_VEW.EV_TRANSACTION_ALL_LOOKUP")] -->|recharge_ev_transaction_transformation| DP_ETL_VEW.EV_TRANSACTION_LD_REJECT[("DP_ETL_VEW.EV_TRANSACTION_LD_REJECT")]
    DP_ETL_VEW.EV_TRANSACTION_REJECT_ALL_LKP[("DP_ETL_VEW.EV_TRANSACTION_REJECT_ALL_LKP")] -->|recharge_ev_transaction_transformation| DP_ETL_VEW.EV_TRANSACTION_LD[("DP_ETL_VEW.EV_TRANSACTION_LD")]
    DP_STG.EV_TRANSACTION_LD[("DP_STG.EV_TRANSACTION_LD")] -->|recharge_ev_transaction_transformation| RCF[("RCF")]
    DP_TAB.DATE_DIM[("DP_TAB.DATE_DIM")]
    DP_TAB.EV_CHANNEL_TYPE_DIM[("DP_TAB.EV_CHANNEL_TYPE_DIM")]
    DP_TAB.SUBSCRIPTION_DIM[("DP_TAB.SUBSCRIPTION_DIM")]
    DP_STG_POS.RETAILER[("DP_STG_POS.RETAILER")]
    DP_TAB.SALES_CHANNEL_DIM[("DP_TAB.SALES_CHANNEL_DIM")]
    DP_ETL_VEW.EV_TRANSACTION_REJECT_ALL_LKP[("DP_ETL_VEW.EV_TRANSACTION_REJECT_ALL_LKP")] -->|recharge_ev_transaction_transformation| DP_ETL_VEW.EV_TRANSACTION_LD_REJECT_TMP[("DP_ETL_VEW.EV_TRANSACTION_LD_REJECT_TMP")]
    dp_stg.x_air_refill[("dp_stg.x_air_refill")] -->|recharge_da_carry_forward| dp_stg.x_da_carry_forward[("dp_stg.x_da_carry_forward")]
    dp_stg.x_air_refill_c2[("dp_stg.x_air_refill_c2")] -->|recharge_da_carry_forward| dp_stg.x_da_carry_forward[("dp_stg.x_da_carry_forward")]
    dp_stg.X_SDP_PERIODIC_ACC_MGMT_RAW[("dp_stg.X_SDP_PERIODIC_ACC_MGMT_RAW")] -->|recharge_da_carry_forward| dp_stg.x_da_carry_forward[("dp_stg.x_da_carry_forward")]
    dp_stg.x_da_carry_forward[("dp_stg.x_da_carry_forward")] -->|recharge_da_carry_forward| DP_TAB.DA_CARRY_FORWARD_FCT[("DP_TAB.DA_CARRY_FORWARD_FCT")]
    BL_PRETUPS_LIVE.USERS[("BL_PRETUPS_LIVE.USERS")] -->|recharge_ev_live_users| DP_STG.EV_LIVE_USERS[("DP_STG.EV_LIVE_USERS")]
    DP_STG.EV_LIVE_USERS[("DP_STG.EV_LIVE_USERS")] -->|recharge_ev_live_users| DP_TAB_EDW.EV_LIVE_USERS[("DP_TAB_EDW.EV_LIVE_USERS")]
    DP_STG.X_EV_RETAILERS[("DP_STG.X_EV_RETAILERS")]
    DP_STG.X_IRIS_ACTIVATION_DUMP[("DP_STG.X_IRIS_ACTIVATION_DUMP")] -->|recharge_extraction_iris_dump| DP_STG.IRIS_Activation_Dump[("DP_STG.IRIS_Activation_Dump")]
    DP_STG.X_IRIS_ACTIVATION_DUMP[("DP_STG.X_IRIS_ACTIVATION_DUMP")]
    DP_STG.IRIS_Activation_Dump[("DP_STG.IRIS_Activation_Dump")]